#!/bin/bash
{
    echo -ne "POST /cgi-bin/wiki.py HTTP/1.1\r\n"
    echo -ne "Host: localhost\r\n"
    echo -ne "Connection: close\r\n"
    echo -ne "Content-Length: 6\r\n"
    echo -ne "\r\n"
    sleep 0.5
    echo -ne "Hello\n"
} | nc localhost 8080

#{
#    echo -ne "GET / HTTP/1.1\r\nHost: localhost\r\n\r\nGET / HTTP/1.1\r\nHost: localhost\r\n\r\n"
#} | nc localhost 8080


