#!/bin/bash
#{
#    echo -ne "POST /test.py HTTP/1.1\r\n"
#    echo -ne "Host: localhost\r\n"
#    echo -ne "Transfer-Encoding: chunked\r\n"
#    echo -ne "\r\n"
#    sleep 0.5
#    echo -ne "7\r\nHello, \r\n"
#    sleep 0.5
#    echo -ne "6\r\nWorld!\r\n"
#    sleep 0.5
#    echo -ne "0\r\n\r\n"
#} | nc localhost 8080

{
    echo -ne "GET / HTTP/1.1\r\nHost: localhost\r\n\r\nGET / HTTP/1.1\r\nHost: localhost\r\n\r\n"
} | nc localhost 8080


